clc; 
clear; 
clf(); 
cd "C:/Users/SUJA/OneDrive/Documents"; 
exec("pf_residue.sci"); 
s=%s; 
N=s+1; 
D=s^2+6*s+25; 
Hc=cont_frm(N,D); 
disp('Controllable form ='); 
ssprint(Hc); 
Ho=syslin('c',(Hc.A)',(Hc.C)',(Hc.B)',Hc.D); 
disp('Observable form ='); 
ssprint(Ho); 
A=diag(roots(D)); 
B=[1;1]; 
C=pf_residue(N,D)'; 
D=Hc.D; 
Hj=syslin('c',A,B,C,D); 
disp('Jordan canonical form ='); 
ssprint(Hj);
